@startuml
title: All schemas
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema
class Klant {
  + url: string
  + bronorganisatie: string
  + klantnummer: string
  + bedrijfsnaam: string
  + functie: string
  + websiteUrl: string
  + voornaam: string
  + voorvoegselAchternaam: string
  + achternaam: string
  + telefoonnummer: string
  + emailadres: string
  + adres: Any
  + subject: string
  + subjectType: string
  + aanmaakkanaal: string
  + geverifieerd: string
  + subjectIdentificatie: Any
}
class BetrokkeneBijKlantcontact {
  + bezoekadres: object
  + correspondentieadres: object
  + klantcontactId: string
  + organisatienaam: string
  + partijId: string
  + persoonsnaam: object
  + rol: string
  + voorkeurskanaal: object
  + voorkeurstaal: object
}
class Partij {
  + bezoekadres: object
  + correspondentieadres: object
  + externeIdentificatie: array
  + interneNotitie: string
  + klanttaakId: array
  + nummer: integer
  + organisatienaam: string
  + persoonsnaam: object
  + voorkeurskanaal: object
  + voorkeurstaal: object
  + wasBereikbaarOp: object
}
class TaakFormulier {
  + type: string
  + value: string
}
class Bijlage {
  + externId: string
  + externRegister: string
  + indicatieWeerTeGeven: boolean
  + klantcontactId: string
  + omschrijving: string
}
class VerblijfAdres {
  + id: string
  + aoaIdentificatie: string
  + wplWoonplaatsNaam: string
  + gorOpenbareRuimteNaam: integer
  + aoaPostcode: string
  + aoaHuisnummer: string
  + aoaHuisletter: string
  + aoaHuisnummertoevoeging: string
  + inpLocatiebeschrijving: string
}
class Actor {
  + klantcontactId: array
  + naam: string
}
class TaakIdentificatie {
  + type: string
  + value: string
}
class Voorkeur {
  + code: string
  + naam: string
}
class Correspondentieadres {
  + aanduidingBijHuisnummer: string
  + adresregelBuitenland1: string
  + adresregelBuitenland2: string
  + adresregelBuitenland3: string
  + antwoordnummer: integer
  + huisletter: string
  + huisnummer: integer
  + huisnummertoevoeging: string
  + land: object
  + postbusnummer: integer
  + postcode: string
  + soortCorrespondentieadres: string
  + straat: string
  + woonplaats: string
}
class Medewerker {
  + klantcontactId: array
  + naam: string
  + eMailadres: string
  + externId: string
  + externRegister: string
  + functie: string
  + telefoonnummer: string
}
class Bericht {
  + id: string
  + gebruikerID: string
  + soortGebruiker: string
  + onderwerp: string
  + berichttekst: string
  + referentie: string
  + handelingsPerspectief: string
  + eindDatumHandelingsTermijn: datetime
  + bijlagen: array
  + geopend: boolean
}
class Klantcontact {
  + actorId: string
  + bijlageId: string
  + gaatOverInterneTaakId: array
  + geregistreerdOp: datetime
  + indicatieContactMislukt: string
  + inhoud: string
  + initiatiefnemer: string
  + interneTaakOntstaanUit: array
  + kanaal: object
  + nummer: integer
  + onderwerp: string
  + plaatsgevondenOp: datetime
}
class Bezoekadres {
  + aanduidingBijHuisnummer: string
  + adresregelBuitenland1: string
  + adresregelBuitenland2: string
  + adresregelBuitenland3: string
  + huisletter: string
  + huisnummer: integer
  + huisnummertoevoeging: string
  + land: object
  + postcode: string
  + soortBezoekadres: string
  + straat: string
  + woonplaats: string
}
class OrganisatorischeEenheid {
  + klantcontactId: array
  + naam: string
  + eMailadres: string
  + externId: string
  + externRegister: string
  + faxnummer: string
  + omschrijving: string
  + telefoonnummer: string
}
class DigitaalAdres {
  + adres: string
  + omschrijving: string
  + soortDigitaalAdres: object
}
class Land {
  + einddatumLand: date
  + ingangsdatumLand: date
  + landcode: string
  + landnaam: string
}
class InterneTaak {
  + actorId: string
  + geregistreerdOp: datetime
  + gevraagdeHandeling: string
  + nummer: integer
  + status: string
}
class SubjectIdentificatie {
  + inpBsn: string
  + anpIdentificatie: string
  + inpANummer: string
  + geslachtsnaam: string
  + voorvoegselGeslachtsnaam: string
  + voorletters: string
  + voornamen: string
  + geslachtsaanduiding: string
  + geboortedatum: string
  + verblijfsadres: Any
  + subVerblijfBuitenland: string
}
class Taak {
  + id: string
  + data: object
  + zaak: string
  + title: string
  + status: string
  + formulier: object
  + verloopdatum: string
  + identificatie: object
  + verzonden_data: object
  + verwerker_taak_id: string
}
class SoortExternId {
  + code: string
  + externRegister: string
  + naam: string
}
class Persoonsnaam {
  + achternaam: string
  + voornaam: string
  + voorvoegselAchternaam: string
}
class ExterneIdentificatie {
  + anderSoortExternId: string
  + externId: string
  + soortExternId: object
}
class KlantAdres {
  + id: string
  + naam: string
  + straatnaam: string
  + huisnummer: integer
  + huisletter: string
  + huisnummertoevoeging: string
  + postcode: string
  + woonplaatsnaam: string
  + landcode: string
}
@enduml
