@startuml
class Voorkeur {
  + code: string
  + naam: string
}
class Partij {
  + bezoekadres: object
  + correspondentieadres: object
  + externeIdentificatie: array
  + interneNotitie: string
  + klanttaakId: array
  + nummer: integer
  + organisatienaam: string
  + persoonsnaam: object
  + voorkeurskanaal: object
  + voorkeurstaal: object
}
class Externe Identificatie {
  + anderSoortExternId: string
  + externId: string
  + soortExternId: object
}
class Land {
  + einddatumLand: date
  + ingangsdatumLand: date
  + landcode: string
  + landnaam: string
}
class Medewerker {
  + klantcontactId: array
  + naam: string
  + eMailadres: string
  + externId: string
  + externRegister: string
  + functie: string
  + telefoonnummer: string
}
class Correspondentieadres {
  + aanduidingBijHuisnummer: string
  + adresregelBuitenland1: string
  + adresregelBuitenland2: string
  + adresregelBuitenland3: string
  + antwoordnummer: integer
  + huisletter: string
  + huisnummer: integer
  + huisnummertoevoeging: string
  + land: object
  + postbusnummer: integer
  + postcode: string
  + soortCorrespondentieadres: string
  + straat: string
  + woonplaats: string
}
class Bezoekadres {
  + aanduidingBijHuisnummer: string
  + adresregelBuitenland1: string
  + adresregelBuitenland2: string
  + adresregelBuitenland3: string
  + huisletter: string
  + huisnummer: integer
  + huisnummertoevoeging: string
  + land: object
  + postcode: string
  + soortBezoekadres: string
  + straat: string
  + woonplaats: string
}
class Actor {
  + klantcontactId: array
  + naam: string
}
class Bijlage {
  + externId: string
  + externRegister: string
  + indicatieWeerTeGeven: boolean
  + klantcontactId: string
  + omschrijving: string
}
class Soort Extern Id {
  + code: string
  + externRegister: string
  + naam: string
}
class Organisatorische Eenheid {
  + klantcontactId: array
  + naam: string
  + eMailadres: string
  + externId: string
  + externRegister: string
  + faxnummer: string
  + omschrijving: string
  + telefoonnummer: string
}
class Digitaal Adres {
  + adres: string
  + omschrijving: string
  + soortDigitaalAdres: object
}
class Persoonsnaam {
  + achternaam: string
  + voornaam: string
  + voorvoegselAchternaam: string
}
class InterneTaak {
  + actorId: string
  + geregistreerdOp: datetime
  + gevraagdeHandeling: string
  + nummer: integer
  + status: string
}
class Klantcontact {
  + actorId: string
  + bijlageId: string
  + gaatOverInterneTaakId: array
  + geregistreerdOp: datetime
  + indicatieContactMislukt: string
  + inhoud: string
  + initiatiefnemer: string
  + interneTaakOntstaanUit: array
  + kanaal: object
  + nummer: integer
  + onderwerp: string
  + plaatsgevondenOp: datetime
}
class BetrokkeneBijKlantcontact {
  + bezoekadres: object
  + correspondentieadres: object
  + klantcontactId: string
  + organisatienaam: string
  + partijId: string
  + persoonsnaam: object
  + rol: string
  + voorkeurskanaal: object
  + voorkeurstaal: object
}
@enduml
