@startuml
title: All schemas
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema
class Voorkeur {
  + code: string
  + naam: string
}
class Klantcontact {
  + nummer: integer
  + onderwerp: string
  + kanaal: object
  + inhoud: string
  + todo: string
  + resultaat: string
  + indicatieContactGelukt: string
  + taal: string
  + vertrouwelijk: string
  + plaatsgevondenOp: datetime
  + actors: array
  + bijlage: array
  + gaatOver: object
  + interneTaakOntstaanUit: array
  + geregistreerdOp: datetime
}
class BetrokenneMedewerkerOfPersoon {
  + naam: string
  + medewerkerIdentificatie: string
  + inpBsn: string
}
class Medewerker {
  + eMailadres: string
  + functie: string
  + telefoonnummer: string
}
class Taak {
  + id: string
  + type: string
  + url: string
  + data: array
  + zaak: string
  + title: string
  + onderwerp: string
  + toelichting: string
  + status: string
  + actie: object
  + verloopdatum: string
  + vervaldatum: string
  + identificatie: object
  + verzonden_data: array
  + verwerker_taak_id: string
  + betrokkenen: array
  + extraData: array
}
class Organisatie {
  + naam: string
}
class Land {
  + einddatumLand: date
  + ingangsdatumLand: date
  + landcode: string
  + landnaam: string
}
class Onderwerpobject {
  + objectIdentificator: object
  + klantContact: object
}
class Betrokenne {
  + betrokkeneType: string
  + rolType: string
  + betrokkene: object
  + partij: object
}
class Correspondentieadres {
  + aanduidingBijHuisnummer: string
  + adresregelBuitenland1: string
  + adresregelBuitenland2: string
  + adresregelBuitenland3: string
  + antwoordnummer: integer
  + huisletter: string
  + huisnummer: integer
  + huisnummertoevoeging: string
  + land: object
  + postbusnummer: integer
  + postcode: string
  + soortCorrespondentieadres: string
  + straat: string
  + woonplaats: string
}
class ExterneIdentificatie {
  + anderePartijIdentificator: string
  + partijIdentificator: object
}
class Actor {
  + klantcontact: array
  + naam: string
  + soortActor: string
  + medewerker: object
  + geautomatiseerdeActor: object
  + organisatorischeEenheid: object
}
class BetrokkeneBijKlantcontact {
  + klantcontact: object
  + partij: object
  + rol: string
  + intitiator: boolean
  + organisatienaam: string
  + contactnaam: object
  + bezoekadres: object
  + correspondentieadres: object
  + communicatiekanaal: object
  + voorkeurstaal: object
}
class TaakIdentificatie {
  + type: string
  + value: string
}
class Identificator {
  + objecttype: string
  + soortObjectId: string
  + objectId: string
  + register: string
}
class OrganisatorischeEenheid {
  + omschrijving: string
  + eMailadres: string
  + telefoonnummer: string
}
class InterneTaak {
  + toegewezenOp: datetime
  + gevraagdeHandeling: string
  + nummer: integer
  + status: string
  + toelichting: string
  + actor: object
  + klantcontact: object
}
class DigitaalAdres {
  + adres: string
  + omschrijving: string
  + soortDigitaalAdres: string
}
class Persoonsnaam {
  + contactnaam: object
}
class Contactnaam {
  + achternaam: string
  + voornaam: string
  + voorvoegselAchternaam: string
  + voorletters: string
}
class Bericht {
  + batchID: string
  + aanmaakDatum: string
  + berichtLeverancierID: string
  + berichtID: string
  + berichtType: string
  + publicatieDatum: string
  + onderwerp: string
  + berichttekst: string
  + referentie: string
  + gebruikerID: string
  + soortGebruiker: string
  + inhoud: string
  + bijlageType: string
  + omschrijving: string
  + volgorde: string
  + partij: object
}
class Partij {
  + nummer: integer
  + interneNotitie: string
  + indicatieGeheimhouding: boolean
  + voorkeurstaal: object
  + indicatieActief: boolean
  + soortPartij: string
  + organisatie: object
  + persoon: object
  + contactpersoon: object
  + voorkeurskanaal: object
  + verstrekteAdressen: array
  + bezoekadres: object
  + correspondentieadres: object
  + externeIdentificaties: array
  + vertegenwoordiger: object
  + vertegenwoordigde: object
  + berichten: array
}
class Contactpersoon {
  + contactnaam: object
  + organisatie: object
}
class Bijlage {
  + objectIdentificator: object
  + klantcontact: object
}
class GeautomatiseerdeActor {
  + functie: string
  + omschrijving: string
}
class Bezoekadres {
  + aanduidingBijHuisnummer: string
  + adresregelBuitenland1: string
  + adresregelBuitenland2: string
  + adresregelBuitenland3: string
  + huisletter: string
  + huisnummer: integer
  + huisnummertoevoeging: string
  + land: object
  + postcode: string
  + soortBezoekadres: string
  + straat: string
  + woonplaats: string
}
@enduml
