@startuml
title: KlantAdres
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class KlantAdres {
  + id: string
  + naam: string
  + straatnaam: string
  + huisnummer: integer
  + huisletter: string
  + huisnummertoevoeging: string
  + postcode: string
  + woonplaatsnaam: string
  + landcode: string
}
@enduml
