@startuml
title: BetrokenneMedewerkerOfPersoon
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class BetrokenneMedewerkerOfPersoon {
  + naam: string
  + medewerkerIdentificatie: string
  + inpBsn: string
}
@enduml
