@startuml
class OrganisatorischeEenheid {
  + klantcontactId: array
  + naam: string
  + eMailadres: string
  + externId: string
  + externRegister: string
  + faxnummer: string
  + omschrijving: string
  + telefoonnummer: string
}
@enduml
