@startuml
title: Bijlage
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Bijlage {
  + externId: string
  + externRegister: string
  + indicatieWeerTeGeven: boolean
  + klantcontactId: string
  + omschrijving: string
}
@enduml
