@startuml
title: SubjectIdentificatie
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class SubjectIdentificatie {
  + inpBsn: string
  + anpIdentificatie: string
  + inpANummer: string
  + geslachtsnaam: string
  + voorvoegselGeslachtsnaam: string
  + voorletters: string
  + voornamen: string
  + geslachtsaanduiding: string
  + geboortedatum: string
  + verblijfsadres: Any
  + subVerblijfBuitenland: string
}
@enduml
