@startuml
title: Persoonsnaam
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Persoonsnaam {
  + achternaam: string
  + voornaam: string
  + voorvoegselAchternaam: string
}
@enduml
