@startuml
title: Land
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Land {
  + einddatumLand: date
  + ingangsdatumLand: date
  + landcode: string
  + landnaam: string
}
@enduml
