@startuml
title: VerblijfAdres
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class VerblijfAdres {
  + id: string
  + aoaIdentificatie: string
  + wplWoonplaatsNaam: string
  + gorOpenbareRuimteNaam: integer
  + aoaPostcode: string
  + aoaHuisnummer: string
  + aoaHuisletter: string
  + aoaHuisnummertoevoeging: string
  + inpLocatiebeschrijving: string
}
@enduml
