@startuml
title: BetrokkeneBijKlantcontact
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class BetrokkeneBijKlantcontact {
  + bezoekadres: object
  + correspondentieadres: object
  + klantcontactId: string
  + organisatienaam: string
  + partijId: string
  + persoonsnaam: object
  + rol: string
  + voorkeurskanaal: object
  + voorkeurstaal: object
}
@enduml
