@startuml
title: ExterneIdentificatie
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class ExterneIdentificatie {
  + anderePartijIdentificator: string
  + partijIdentificator: object
}
@enduml
