@startuml
title: Contactnaam
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Contactnaam {
  + achternaam: string
  + voornaam: string
  + voorvoegselAchternaam: string
  + voorletters: string
}
@enduml
