@startuml
title: InterneTaak
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class InterneTaak {
  + actorId: string
  + geregistreerdOp: datetime
  + gevraagdeHandeling: string
  + nummer: integer
  + status: string
}
@enduml
