@startuml
title: Partij
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Partij {
  + nummer: integer
  + interneNotitie: string
  + indicatieGeheimhouding: boolean
  + voorkeurstaal: object
  + indicatieActief: boolean
  + soortPartij: string
  + organisatie: string
  + persoon: object
  + contactpersoon: object
  + voorkeurskanaal: object
  + verstrekteAdressen: array
  + bezoekadres: object
  + correspondentieadres: object
  + externeIdentificatie: array
  + vertegenwoordiger: object
  + vertegenwoordigde: object
}
@enduml
