@startuml
title: Betrokenne
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Betrokenne {
  + betrokkeneType: string
  + rolType: string
  + betrokkene: object
}
@enduml
