@startuml
title: Partij
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Partij {
  + nummer: integer
  + interneNotitie: string
  + indicatieGeheimhouding: boolean
  + voorkeurstaal: object
  + indicatieActief: boolean
  + soortPartij: string
  + organisatienaam: string
  + persoonsnaam: object
  + voorkeurskanaal: object
  + verstrekteAdressen: array
  + bezoekadres: object
  + correspondentieadres: object
  + externeIdentificatie: array
  + klanttaakId: array
}
@enduml
