@startuml
title: Taak
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Taak {
  + id: string
  + type: string
  + url: string
  + data: array
  + zaak: string
  + title: string
  + onderwerp: string
  + toelichting: string
  + status: string
  + actie: object
  + verloopdatum: string
  + vervaldatum: string
  + identificatie: object
  + verzonden_data: array
  + verwerker_taak_id: string
  + betrokkenen: array
}
@enduml
