@startuml
title: Klantcontact
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Klantcontact {
  + nummer: integer
  + onderwerp: string
  + plaatsgevondenOp: datetime
  + actor: object
  + bijlage: array
  + gaatOverInterneTaak: object
  + geregistreerdOp: datetime
  + inhoud: string
  + indicatieContactGelukt: string
  + initiatiefnemer: string
  + interneTaakOntstaanUit: array
  + kanaal: object
}
@enduml
