@startuml
title: InterneTaak
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class InterneTaak {
  + toegewezenOp: datetime
  + gevraagdeHandeling: string
  + nummer: integer
  + status: string
  + toelichting: string
  + actor: object
  + klantcontact: object
}
@enduml
