@startuml
title: Bericht
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Bericht {
  + batchID: string
  + aanmaakDatum: string
  + berichtLeverancierID: string
  + berichtID: string
  + berichtType: string
  + publicatieDatum: string
  + onderwerp: string
  + berichttekst: string
  + referentie: string
  + gebruikerID: string
  + soortGebruiker: string
  + inhoud: string
  + bijlageType: string
  + omschrijving: string
  + volgorde: string
  + partij: object
  + betrokkene: object
}
@enduml
