@startuml
title: Bericht
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Bericht {
  + id: string
  + gebruikerID: string
  + soortGebruiker: string
  + onderwerp: string
  + berichttekst: string
  + referentie: string
  + handelingsPerspectief: string
  + eindDatumHandelingsTermijn: datetime
  + bijlagen: array
  + geopend: boolean
}
@enduml
