@startuml
title: Medewerker
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Medewerker {
  + klantcontactId: array
  + naam: string
  + eMailadres: string
  + externId: string
  + externRegister: string
  + functie: string
  + telefoonnummer: string
}
@enduml
