@startuml
title: OrganisatorischeEenheid
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class OrganisatorischeEenheid {
  + omschrijving: string
  + eMailadres: string
  + telefoonnummer: string
}
@enduml
