@startuml
title: BetrokkeneBijKlantcontact
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class BetrokkeneBijKlantcontact {
  + klantcontact: object
  + partij: object
  + rol: string
  + intitiator: boolean
  + organisatienaam: string
  + contactnaam: object
  + bezoekadres: object
  + correspondentieadres: object
  + communicatiekanaal: object
  + voorkeurstaal: object
}
@enduml
