@startuml
title: Actor
footer: Common Gateway Plugin | Commongateway | Customerinteractionbundle 
header: Schema

class Actor {
  + klantcontact: array
  + naam: string
  + soortActor: string
  + medewerker: object
  + geautomatiseerdeActor: object
  + organisatorischeEenheid: object
}
@enduml
