@startuml
title Lagen model voor klant interacties

!define RECTANGLE class

RECTANGLE "Klant Interactie Component" {
  RECTANGLE "Laag 1: Data Opslag" {
    - Object Store Oplossing (MongoDB)
  }

  RECTANGLE "Laag 4: API's" {
    - Adapter naar Klant Interactie CRUD API's
  }

  RECTANGLE "Laag 3: Integratie" {
    - Integratie van Diverse Gegevensbronnen
    - Brononafhankelijke Serviceaanbieding
    - Bronoverstijgende Extensie zonder Koppeling van Registers
  }
}


@enduml