@startuml
actor Medewerker
actor Klant
participant Zaaksysteem
participant KTB as "Takenregister "
participant Klanten as "Klantenregister"
participant Berichten as "Berichtenregister"
participant "Afhandelcomponent"
participant MijnOmgeving

Klant -> MijnOmgeving: Log in op MijnOmgeving
Klant -> MijnOmgeving: Vraag een product aan
MijnOmgeving -> Zaaksysteem: Creëer zaak
Medewerker -> Medewerker: Neemt zaak in behandeling
Medewerker -> Medewerker: Beoordeel zaak
Medewerker -> Medewerker: Constateer dat extra document nodig is

Medewerker -> Zaaksysteem: Maak verzoek tot aanvulling aan (extra document)
Zaaksysteem -> KTB: Schrijf taak weg in Takenregister (Zaakspecifiek voorkeurskanaal in extraData-veld)
KTB -> "Afhandelcomponent": Stuur event "Nieuwe taak" naar Afhandelcomponent
"Afhandelcomponent" -> KTB: Haalt taak op uit Takenregister 
"Afhandelcomponent" -> Klanten: Haalt klant op uit het Klantenregister (tbv Voorkeurskanaal als niet gevuld in taak)
"Afhandelcomponent" -> "Afhandelcomponent": Creëer bericht
"Afhandelcomponent" -> Klant: Verstuur bericht via voorkeurskanaal
"Afhandelcomponent" -> Berichten: Sla bericht op in Berichtenregister

Klant -> MijnOmgeving: Log in op MijnOmgeving
MijnOmgeving -> KTB: Haalt taak op uit Takenregister
Klant -> MijnOmgeving: Voer taak uit door document te uploaden
MijnOmgeving -> KTB: Update taakstatus in Takenregister naar "gesloten"
MijnOmgeving -> Zaaksysteem: Voeg document toe aan Zaaksysteem


Zaaksysteem -> Medewerker: Notificeer medewerker over toegevoegd document
Medewerker -> Medewerker: Beoordeelt document
Medewerker -> Medewerker: Accepteert document
Medewerker -> Zaaksysteem: Zet zaak naar volgende status
Zaaksysteem -> "Afhandelcomponent": Stuur event "update zaakstatus" naar Afhandelcomponent
"Afhandelcomponent" -> Zaaksysteem: Haal zaak op a.h.v. "update zaakstatus" (inclusief zaak voorkeurskanaal)
"Afhandelcomponent" -> Klanten: Haalt klant op uit Klantenregister
"Afhandelcomponent" -> "Afhandelcomponent": Creëer bericht
"Afhandelcomponent" -> Klant: Verstuur bericht via voorkeurskanaal
"Afhandelcomponent" -> Berichten: Sla bericht op in Berichtenregister
@enduml
