# Generates SVG files from UML files (for documentation purposes)
name: generate plantuml
on: push
jobs:
  generate-plantuml:
    runs-on: ubuntu-latest
    name: Generate plant UML files
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}